---
title: "01_process_data"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(haven)
library(broom)
library(broom.helpers)    # Add empty reference categories to tidy model data frames
library(ggforce) 
library(survey)
library(marginaleffects)
library(scales)  

# df_cand <- read_dta('repl/candidate.dta')
```

## Load Data

```{r}
disagree_vals <- c("Somewhat Disagree", "Strongly disagree", "Neither agree nor disagree")
agree_vals <- c("Somewhat agree", "Strongly agree")
petitionA <- c("Q12", "Q39", "Q53")
petitionB <- c("Q15", "Q41", "Q59")
petitionC <- c("Q25", "Q45", "Q55")
petitionD <- c("Q24", "Q47", "Q61")

question1_vars <- c("var_P1a", "var_P2a", "var_P3a", "var_P4a")
question2_vars <- c("var_P1b", "var_P2b", "var_P3b", "var_P4b")

titles <- c("A" = "Stop Cyanide Fishing: Save the Humphead Wrasse",
            "B" = "Enforce Cyanide Fishing Bans and Protect the Humphead Wrasse",
            "C" = "No Fishing, Save the Parrotfish!",
            "D" = "The Parrotfish Should Live!")

df %>% 
  names()
```
```{r}
df <- read_csv('CMC+Change.org_April+30,+2025_21.56.csv', skip=0) %>% 
  filter(`StartDate` != '{"ImportId":"startDate","timeZone":"America/Denver"}' &
           `StartDate` != "Start Date") %>% 
  mutate(across(c("RecordedDate", "StartDate", "EndDate"), ~ymd_hms(.))) %>% 
  filter(Status == "IP Address")  %>% 
  filter(StartDate >= ymd("2025-04-16")) %>% 
  mutate(pair_order = coalesce(FL_26_DO, FL_27_DO, FL_28_DO)) %>% 
  separate(pair_order, c("first_pair", "second_pair"), sep="\\|") %>% 
  mutate(pair1_order = coalesce(`PetitionPair1-AB_DO`, `PetitionPair2-AC_DO`, `PetitionPair3-A/D_DO`),
         pair2_order = coalesce(`PetitionPair1-CD_DO`, `PetitionPair2-BD_DO`, `PetitionPair3-B/C_DO`)) %>% 
  separate(pair1_order, c("var_P1", "var_P1a", "var_P1b", 
                          "var_P2", "var_P2a", "var_P2b", 
                          "var_selection1"), sep="\\|") %>%
  separate(pair2_order, c("var_P3", "var_P3a", "var_P3b", 
                          "var_P4", "var_P4a", "var_P4b", 
                          "var_selection2"), sep="\\|") %>% 
  mutate(across(question1_vars, ~str_c(., "_1"), .names = "{.col}_1")) %>% 
  mutate(across(question1_vars, ~str_c(., "_2"), .names = "{.col}_2")) %>% 
  mutate(across(question2_vars, ~str_c(., "_1"), .names = "{.col}_1")) %>% 
  mutate(across(question2_vars, ~str_c(., "_2"), .names = "{.col}_2")) %>% 
  rowwise() %>% 
  mutate(across(str_c(question1_vars, "_1"), ~get(.), 
                .names="subject_matter_expert{str_extract(col, 'P[0-9]')}")) %>% 
  mutate(across(str_c(question1_vars, "_2"), ~get(.), 
                .names="author_committed{str_extract(col, 'P[0-9]')}")) %>% 
  mutate(across(str_c(question2_vars, "_1"), ~get(.), 
                .names="persuade_undecided{str_extract(col, 'P[0-9]')}")) %>% 
  mutate(across(str_c(question2_vars, "_2"), ~get(.), 
                .names="motivate_reader{str_extract(col, 'P[0-9]')}")) %>% 
  ungroup() %>% 
  mutate(pass_attention = case_when(str_detect(Q5, "AI-generated drafting") &
                                      FL_3_DO == 'AI-Primed' ~ 1,
                                    !str_detect(Q8, "AI-generated drafting") &
                                      FL_3_DO == 'Control' ~ 1,
                                    TRUE ~ 0),
         AI_primed = if_else(FL_3_DO == "AI-Primed", 1, 0)) %>%
  rowwise() %>%
  mutate(selection1 = get(var_selection1),
         selection2 = get(var_selection2)) %>%
  ungroup() %>% 
mutate(across(c("var_P1", "var_P2", "var_P3", "var_P4"), 
              ~case_when(
  . %in% petitionA ~ "A",
  . %in% petitionB ~ "B",
  . %in% petitionC ~ "C",
  . %in% petitionD ~ "D"),
              .names="petition{str_replace(col, 'var_', '')}")) %>% 
  pivot_longer(cols = c(str_c("petitionP", 1:4),
                        str_c("subject_matter_expert", str_c("P", 1:4)),
                        str_c("author_committed", str_c("P", 1:4)),
                        str_c("persuade_undecided", str_c("P", 1:4)),
                        str_c("motivate_reader", str_c("P", 1:4))), 
               names_to=c("type", "petition_order"),
               names_pattern=c("(.*)(P[0-9])"),
               values_to="response") %>% 
  mutate(petition_order = str_extract(petition_order, "(?<=P)[0-9]") %>% 
           as.numeric()) %>% 
  pivot_wider(names_from = c("type"), values_from = c("response")) %>%
  mutate(selected_petition = if_else(petition_order %in% c(1,2),
                                     names(titles)[match(selection1, titles)]==petition,
                                     names(titles)[match(selection2, titles)]==petition) %>% 
           as.numeric()) %>% 
  mutate(long_petition = if_else(petition %in% c("B", "D"), 0, 1),
         good_title = if_else(petition %in% c("A", "B"), 1, 0 ))
```

```{r}
df %>% 
  summarize(pass_attention = mean(pass_attention),
            per_AI_primed = mean(AI_primed))
```
```{r}
df_model_overall <- lm(selected_petition ~ long_petition + good_title, data = df)
tidy(df_model_overall)

df_model <- lm(selected_petition ~ long_petition + good_title, data = df %>% 
                 filter(AI_primed==0))
tidy(df_model)

df_model_AI <- lm(selected_petition ~ long_petition + good_title, data = df %>% 
                    filter(AI_primed==1))
tidy(df_model_AI)

df %>% 
  group_by(AI_primed, long_petition) %>% 
  summarize(avg = mean(selected_petition, na.rm = T))

df %>% 
  group_by(AI_primed, good_title) %>% 
  summarize(avg = mean(selected_petition, na.rm = T))

bind_rows(
  bind_rows(
  tidy(lm(selected_petition ~ 0 + long_petition, data = filter(df, AI_primed==1))),
  tidy(lm(selected_petition ~ 0 + good_title, data = filter(df, AI_primed==1)))
) %>% 
  mutate(type = "AI_primed"),

bind_rows(
  tidy(lm(selected_petition ~ 0 + long_petition, data = filter(df, AI_primed==0))),
  tidy(lm(selected_petition ~ 0 + good_title, data = filter(df, AI_primed==0)))
) %>% 
  mutate(type = "No AI priming")
)
```
```{r}
df_model %>%
  tidy_and_attach()
```
```{r}
df_model %>%
  tidy_and_attach() %>% 
  tidy_add_reference_rows() %>%
  tidy_add_estimate_to_reference_rows() %>%
  filter(term != "(Intercept)") %>%
  ggplot(aes(x = estimate, y = term)) +
  geom_pointrange(aes(xmin = conf.low, xmax = conf.high)) +
  # annotate(
  #   geom = "errorbar",
  #   x = 0, xmin = 0, xmax = 683.4, y = 1.5,
  #   width = 0.1, color = "grey70"
  # ) +
  # annotate(
  #   geom = "label",
  #   x = 683.4 / 2, y = 1.5,
  #   label = "683.4 grams",
  #   size = 3
  # ) +
  labs(
    x = "Estimate", y = NULL,
    title = "Relative shift in average",
    subtitle = "Similar to AMCEs"
  ) +
  theme_classic()
```
```{r}
model_logit <- glm(
  selected_petition ~ long_petition + good_title, data = df %>% filter(AI_primed==1,
                                                                       !is.na(selected_petition)),
  family = binomial(link = "logit")
)

mfx_logit <- model_logit %>% 
  avg_slopes()

mfx_logit
```
```{r}
rhs_vars <- all.vars(stats::update(formula(model_logit), 0 ~ .))

model_variable_levels <- tibble(
  variable = rhs_vars
) %>% 
  mutate(levels = map(variable, ~{
    x <- df[[.x]]
    if (is.numeric(x)) {
      as.character(unique(x))
    } else if (is.factor(x)) {
      levels(x)
    } else {
      sort(unique(x))
    }
  })) %>% 
  unnest(levels) %>% 
  mutate(term = paste0(variable, levels))

label_pp <- label_number(accuracy = 1, scale = 100, 
                         suffix = " pp.", style_negative = "minus")

label_amce <- label_number(accuracy = 0.1, scale = 100, suffix = " pp.", 
                           style_negative = "minus", style_positive = "plus")

```
```{r}
model_results_logit_mfx <- mfx_logit %>%
  separate_wider_delim(
    contrast,
    delim = " - ", 
    names = c("variable_level", "reference_level")
  )

variable_lookup <- tribble(
  ~variable,    ~variable_nice,
  "good_title", "Good title",
  "long_petition", "Long petition",
) %>% 
  mutate(variable_nice = fct_inorder(variable_nice))

# Combine full dataset of factor levels with marginal effects
plot_data_logit_mfx <- model_variable_levels %>%
  left_join(
    model_results_logit_mfx,
    by = join_by(variable == term, levels == variable_level)
  ) %>%
  # Make these zero
  mutate(
    across(
      c(estimate, conf.low, conf.high),
      ~ ifelse(is.na(.x), 0, .x)
    )
  ) %>% 
  left_join(variable_lookup, by = join_by(variable)) %>% 
  mutate(across(c(levels, variable_nice), ~fct_inorder(.)))

plot_data_logit_mfx
```

```{r}
ggplot(
  plot_data_logit_mfx,
  aes(x = estimate, y = levels, color = variable_nice)
) +
  geom_vline(xintercept = 0) +
  geom_pointrange(aes(xmin = conf.low, xmax = conf.high)) +
  scale_x_continuous(labels = label_pp) +
  guides(color = "none") +
  labs(
    x = "Percentage point change in probability of petition selection",
    y = NULL,
    title = "AMCEs from logistic regression marginal effects"
  ) +
  facet_col(facets = "variable_nice", scales = "free", space = "free")
```




