---
title: "R Notebook"
---

```{r}
library(tidyverse)
library(haven)
library(broom)
library(ggforce) 
library(survey)
library(marginaleffects)
library(scales)  
library(ggstats)
library(ggthemes)
library(xtable)
library(cregg)
library(stargazer)

source("01_process_data_script.R", local = knitr::knit_global())

cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

```

```{r}
df <- process_qualtrics('data/CMC+Change.org_May+12,+2025_07.16.csv',
                        min_date = "2025-04-21")

prescreen <- read_csv('data/prescreen_data_20250512.csv', skip = 1)
prescreen

print(xtable(prop.table(table(prescreen$Gender)) * 100))
print(prop.table(table(prescreen$Race)) * 100)
print(prop.table(table(prescreen$College)) * 100)
print(prop.table(table(prescreen$`Social Media`)) * 100)

prescreen %>% 
  pivot_longer(c("Gender", "Race", "College", "Social Media")) %>% 
  group_by(name, value) %>% 
  summarize(n = n()) %>% 
  group_by(name) %>% 
  mutate(pct = 100*n /sum(n)) %>% 
  ungroup() %>% 
  ggplot() +
  geom_col(aes(value, pct, fill=name)) +
  #facet_grid(cols="name", scales="free_x", axes="all_x") +
  facet_grid(.~name, scales = "free_x", space = "free") +
  scale_fill_manual(values=cbPalette) +
  theme_minimal() + 
  labs(x="Category", y = "Percent of participants",
       fill="") +
  theme(axis.text.x = element_text(angle = -90, vjust = 0.5, hjust=1))

ggsave("participants.pdf", height=10, width=10)

prescreen %>% 
  nrow()
```
## Descriptive Plots
Describe AI Primed category 
```{r}

## Prepare Likert data for Q13
df <- df %>% 
  rename(ai_is_appropriate = Q13,
         is_conservation_committed = Q14)

df %>% 
  distinct(ResponseId, AI_primed) %>% 
  group_by(AI_primed) %>% 
  summarize(n = n())
```


```{r}
ai_likert_summary <- df %>%
  distinct(ResponseId, AI_primed, ai_is_appropriate) %>%
  group_by(AI_primed, ai_is_appropriate) %>%
  summarise(count = n(), .groups = "keep") %>%
  group_by(AI_primed) %>%
  mutate(percentage = count / sum(count) * 100) %>%
  ungroup()

ai_likert <- df %>%
  distinct(ResponseId, AI_primed, ai_is_appropriate) %>%
  mutate(
    ai_is_appropriate_broad = case_when(
      ai_is_appropriate == "Strongly disagree" ~ "Disagree", 
      ai_is_appropriate == "Somewhat disagree" ~ "Disagree",
      ai_is_appropriate == "Neither agree nor disagree" ~ "Neither agree nor disagree",
      ai_is_appropriate == "Somewhat agree" ~ "Agree",
      ai_is_appropriate == "Strongly agree" ~ "Agree",
      TRUE ~ NA
    ),
    ai_approp_agree = if_else(ai_is_appropriate_broad == 'Agree', 1, 0)
  )

ai_likert$ai_is_appropriate_broad <- factor(ai_likert$ai_is_appropriate_broad,
                              levels = c("Disagree",
                                         "Neither agree nor disagree",
                                         "Agree"))

ai_likert$AI_primed <- factor(ai_likert$AI_primed,
                              levels = c(0,1),
                              labels = c("Control", "AI-Primed"))


gglikert(ai_likert,
         include = ai_is_appropriate_broad,
         facet_rows = vars(AI_primed),
         symmetric = TRUE,
         add_totals = FALSE) +
  ggtitle("It is appropriate to use AI when writing a petition.") +
  theme_minimal() + 
    theme(
    axis.text.y = element_blank())

ggsave("ai_likert.pdf", width=10)

gglikert(ai_likert,
         include = ai_is_appropriate_broad,
         #symmetric = TRUE,
         add_totals = FALSE) +
  ggtitle("It is appropriate to use AI when writing a petition.") +
  theme_minimal() + 
    theme(
    axis.text.y = element_blank())

lm(ai_approp_agree~AI_primed, data=ai_likert) %>% 
  summary()
```

Marignal means


```{r}
df_mm <- df
df_mm$long_petition <- factor(df_mm$long_petition,
                           levels = c(0,1),
                           labels = c("Short", "Long"))
df_mm$good_title <- factor(df_mm$good_title,
                        levels = c(0,1),
                        labels = c("Bad","Good"))

overall_mm <- bind_rows(
  tidy(lm(selected_petition ~ 0 + good_title, 
          data = df_mm),
       conf.int = TRUE),
  tidy(lm(selected_petition ~ 0 + long_petition,
          data = df_mm),
       conf.int = TRUE)
) %>%
  mutate(
    petition_attribute = case_when(
    term %in% c("good_titleBad", "good_titleGood") ~ "Title Quality",
    term %in% c("long_petitionShort", "long_petitionLong") ~ "Petition Length"
  ),
  attribute_value = case_when(
    term == "good_titleBad" ~ "Bad Title",
    term == "good_titleGood" ~ "Good Title",
    term == "long_petitionShort" ~ "Short Petition",
    term == "long_petitionLong" ~ "Long Petition"
  )
  )

lm(selected_petition ~ long_petition, 
          data = df_mm %>% filter(AI_primed == 1)) %>% 
  summary()

lm(selected_petition ~ long_petition, 
          data = df_mm %>% filter(AI_primed == 0)) %>% 
  summary()

ai_mm <- bind_rows(
  tidy(lm(selected_petition ~ 0 + good_title, 
          data = df_mm %>% filter(AI_primed == 1)),
       conf.int = TRUE),
  tidy(lm(selected_petition ~ 0 + long_petition, 
          data = df_mm %>% filter(AI_primed == 1)),
       conf.int = TRUE)) %>%
  mutate(
    petition_attribute = case_when(
    term %in% c("good_titleBad", "good_titleGood") ~ "Title Quality",
    term %in% c("long_petitionShort", "long_petitionLong") ~ "Petition Length"
  ),
  attribute_value = case_when(
    term == "good_titleBad" ~ "Bad Title",
    term == "good_titleGood" ~ "Good Title",
    term == "long_petitionShort" ~ "Short Petition",
    term == "long_petitionLong" ~ "Long Petition"
  )
  ) 

control_mm <- bind_rows(
  tidy(lm(selected_petition ~ 0 + good_title, data = df_mm %>% filter(AI_primed == 0)),
       conf.int = TRUE),
  tidy(lm(selected_petition ~ 0 + long_petition, data = df_mm %>% filter(AI_primed == 0)),
       conf.int = TRUE)) %>% 
  mutate(
    petition_attribute = case_when(
    term %in% c("good_titleBad", "good_titleGood") ~ "Title Quality",
    term %in% c("long_petitionShort", "long_petitionLong") ~ "Petition Length"
  ),
  attribute_value = case_when(
    term == "good_titleBad" ~ "Bad Title",
    term == "good_titleGood" ~ "Good Title",
    term == "long_petitionShort" ~ "Short Petition",
    term == "long_petitionLong" ~ "Long Petition"
  ))

overall_mm_plot <- overall_mm %>%
  ggplot(aes(x = estimate, y = attribute_value, color = petition_attribute)) +
  geom_pointrange(aes(xmin = conf.low, xmax = conf.high)) +
  geom_vline(xintercept = 0, color = "grey", linetype = 2) + 
  scale_x_continuous(labels = label_comma()) +
  labs(
    x = "Marginal Mean", y = NULL, 
    title = "Overall"
  ) + 
  guides(color = guide_legend(title = "Petition Attribute")) +
  theme_minimal()

ai_mm_plot <- ai_mm %>%
  ggplot(aes(x = estimate, y = attribute_value, color = petition_attribute)) +
  geom_pointrange(aes(xmin = conf.low, xmax = conf.high)) +
  geom_vline(xintercept = 0, color = "grey", linetype = 2) + 
  scale_x_continuous(labels = label_comma()) +
  labs(
    x = "Marginal Mean", y = NULL, 
    title = "Treatment Group"
  ) + 
  guides(color = guide_legend(title = "Petition Attribute")) +
  theme_minimal()

control_mm_plot <- control_mm %>%
  ggplot(aes(x = estimate, y = attribute_value, color = petition_attribute)) +
  geom_pointrange(aes(xmin = conf.low, xmax = conf.high)) +
  geom_vline(xintercept = 0, color = "grey", linetype = 2) + 
  scale_x_continuous(labels = label_comma()) +
  labs(
    x = "Marginal Mean", y = NULL, 
    title = "Control Group"
  ) + 
  guides(color = guide_legend(title = "Petition Attribute")) +
  theme_minimal()

overall_mm_plot 
ggsave("overall_mm.pdf")
ai_mm_plot
ggsave("ai_mm.pdf")
control_mm_plot
ggsave("control_mm.pdf")
```

## Causal Plots

Producing the AMCE using a linear model

```{r}
df %>% 
  summarize(pass_attention = mean(pass_attention),
            per_AI_primed = mean(AI_primed))
```


```{r}
df_model_overall <- lm(selected_petition ~ long_petition + good_title, data = df)
tidy(df_model_overall)

df_model <- lm(selected_petition ~ long_petition + good_title, data = df %>% 
                 filter(AI_primed==0))
tidy(df_model)

df_model_AI <- lm(selected_petition ~ long_petition + good_title, data = df %>% 
                    filter(AI_primed==1))
tidy(df_model_AI)

df %>% 
  group_by(AI_primed, long_petition) %>% 
  summarize(avg = mean(selected_petition, na.rm = T))

df %>% 
  group_by(AI_primed, good_title) %>% 
  summarize(avg = mean(selected_petition, na.rm = T))

bind_rows(
  bind_rows(
  tidy(lm(selected_petition ~ 0 + long_petition, data = filter(df, AI_primed==1))),
  tidy(lm(selected_petition ~ 0 + good_title, data = filter(df, AI_primed==1)))
) %>% 
  mutate(type = "AI_primed"),

bind_rows(
  tidy(lm(selected_petition ~ 0 + long_petition, data = filter(df, AI_primed==0))),
  tidy(lm(selected_petition ~ 0 + good_title, data = filter(df, AI_primed==0)))
) %>% 
  mutate(type = "No AI priming")
)

df_model %>%
  tidy_and_attach()

df_model <- df_model %>%
  tidy_and_attach() %>% 
  tidy_add_reference_rows() %>%
  tidy_add_estimate_to_reference_rows() %>%
  filter(term != "(Intercept)")

df_model$term <- factor(df_model$term,
                         levels = c("long_petition", "good_title"),
                         labels = c("Petition Length", "Title Quality"))

amce_plot <- ggplot(df_model, aes(x = estimate, y = term, colour = term)) +
  geom_pointrange(aes(xmin = conf.low, xmax = conf.high)) +
  geom_vline(xintercept = 0, color = "grey", linetype = 2) + 
  labs(
    x = "Estimated AMCE", y = NULL
  ) + 
  guides(color = guide_legend(title = "Petition Attribute")) + 
  theme_classic()

amce_plot

ggsave("amce_linear.pdf")
```

Version using `cregg`

```{r}
cregg_plot <- function(df, treatment_val=1, outcome_var, title=NA) {
  df_amce <- df %>% 
    rename(outcome = outcome_var) %>% 
    filter(AI_primed==treatment_val) %>% 
    mutate(
           `Long Petition` = factor(long_petition, levels=c(0,1),
                                  labels=c('Short', 'Long')),
           `Good Title` = factor(good_title, levels=c(0,1),
                               labels=c('Bad', 'Good'))
           ) 
  
  model_amce <- amce(
    df_amce,
    outcome ~ `Long Petition` + `Good Title`,
    id = ~ResponseId
  )
  
  print(model_amce)
  model_amce %>% as_tibble()
  plt <- plot(model_amce) + 
    guides(color = "none") +
    theme_minimal()
  if (!is.na(title)) {
    plt <- plt +
      labs(title = title)
  }
  
  print(plt)
  ggsave(str_glue('amce_cregg_{treatment_val}.pdf'))
}
cregg_plot(df, 1, "selected_petition")
cregg_plot(df, 0, "selected_petition")
```

```{r}
df_scalevars <- df %>% 
  mutate(across(c(subject_matter_expert,author_committed, persuade_undecided,
                  motivate_reader), .fns = lst(agree = ~if_else(. %in% agree_vals, 1, 0))))

cregg_plot(df_scalevars, 1, "subject_matter_expert_agree",
           "Petition author is a subject matter expert...")
cregg_plot(df_scalevars, 0, "subject_matter_expert_agree",
           "Petition author is a subject matter expert...")

cregg_plot(df_scalevars, 1, "author_committed_agree",
           "Petition author is committed to the cause...")
cregg_plot(df_scalevars, 0, "author_committed_agree",
           "Petition author is committed to the cause...")

cregg_plot(df_scalevars, 1, "persuade_undecided_agree",
           "Petition could persuade someone undecided...")
cregg_plot(df_scalevars, 0, "persuade_undecided_agree",
           "Petition could persuade someone undecided...")

cregg_plot(df_scalevars, 1, "motivate_reader_agree",
           "Petition would motivate a reader...")
cregg_plot(df_scalevars, 0, "motivate_reader_agree",
           "Petition would motivate a reader...")

```
```{r}
logit_mfx_plot <- function(df, treatment_val=1, outcome_var, title=NA) {
  df <- df %>% 
    rename(outcome = outcome_var)
  
  model_logit <- glm(
    outcome ~ long_petition + good_title, data = df %>% 
      filter(AI_primed==treatment_val),
    family = binomial(link = "logit")
  ) 
  
  mfx_logit <- model_logit %>% 
    avg_slopes()
  
  rhs_vars <- all.vars(stats::update(formula(model_logit), 0 ~ .))
  
  model_variable_levels <- tibble(
  variable = rhs_vars
) %>% 
  mutate(levels = map(variable, ~{
    x <- df[[.x]]
    if (is.numeric(x)) {
      as.character(unique(x))
    } else if (variable=='long_petition') {
      factor(x, levels=c(0,1),
                                  labels=c('Short', 'Long'))
    } else if (variable=='good_title') {
      factor(x, levels=c(0,1),
                                  labels=c('Bad', 'Good'))
    } else {
      sort(unique(x))
    }
  })) %>% 
  unnest(levels) %>% 
  mutate(term = paste0(variable, levels))
  
  label_pp <- label_number(accuracy = 1, scale = 100, 
                         suffix = " pp.", style_negative = "minus")

  label_amce <- label_number(accuracy = 0.1, scale = 100, suffix = " pp.", 
                             style_negative = "minus", style_positive = "plus")
  
  model_results_logit_mfx <- mfx_logit %>%
  separate_wider_delim(
    contrast,
    delim = " - ", 
    names = c("variable_level", "reference_level")
  )
  variable_lookup <- tribble(
  ~variable,    ~variable_nice,
  "good_title", "Good title",
  "long_petition", "Long petition",
) %>% 
  mutate(variable_nice = fct_inorder(variable_nice))

# Combine full dataset of factor levels with marginal effects
plot_data_logit_mfx <- model_variable_levels %>%
  left_join(
    model_results_logit_mfx,
    by = join_by(variable == term, levels == variable_level)
  ) %>%
  # Make these zero
  mutate(
    across(
      c(estimate, conf.low, conf.high),
      ~ ifelse(is.na(.x), 0, .x)
    )
  ) %>% 
  left_join(variable_lookup, by = join_by(variable)) %>% 
  mutate(across(c(levels, variable_nice), ~fct_inorder(.))) %>% 
  mutate(levels_nice = case_when(variable=='long_petition' & levels==0 ~ 'Short',
                                 variable=='long_petition' & levels==1 ~ 'Long',
                                 variable=='good_title' & levels==0 ~ 'Bad',
                                 variable=='good_title' & levels==1 ~ 'Good'))

plt <- ggplot(
  plot_data_logit_mfx,
  aes(x = estimate, y = levels_nice, color = variable_nice)
) +
  geom_vline(xintercept = 0) +
  geom_pointrange(aes(xmin = conf.low, xmax = conf.high)) +
  scale_x_continuous(labels = label_pp) +
  guides(color = "none") +
  labs(
    x = "Percentage point change in probability of petition selection",
    y = NULL,
    title = "AMCEs from logistic regression"
  ) +
  facet_col(facets = "variable_nice", scales = "free_y", space = "free") +
  theme_minimal()

if (!is.na(title)) {
    plt <- plt +
      labs(title = title)
  }
print(plt)
ggsave(str_glue("amce_mfx_{treatment_val}_{outcome_var}.pdf"))
}

logit_mfx_plot(df, 1, "selected_petition")
logit_mfx_plot(df, 0, "selected_petition")
```



```{r}
logit_mfx_plot(df_scalevars, 1, "subject_matter_expert_agree",
           "Petition author is a subject matter expert...")
logit_mfx_plot(df_scalevars, 0, "subject_matter_expert_agree",
           "Petition author is a subject matter expert...")

logit_mfx_plot(df_scalevars, 1, "author_committed_agree",
           "Petition author is committed to the cause...")
logit_mfx_plot(df_scalevars, 0, "author_committed_agree",
           "Petition author is committed to the cause...")

logit_mfx_plot(df_scalevars, 1, "persuade_undecided_agree",
           "Petition could persuade someone undecided...")
logit_mfx_plot(df_scalevars, 0, "persuade_undecided_agree",
           "Petition could persuade someone undecided...")

logit_mfx_plot(df_scalevars, 1, "motivate_reader_agree",
           "Petition would motivate a reader...")
logit_mfx_plot(df_scalevars, 0, "motivate_reader_agree",
           "Petition would motivate a reader...")
```

```{r}
df_other_outcomes <- df
# df_other_outcomes$long_petition <- factor(df_other_outcomes$long_petition,
#                            levels = c(0,1),
#                            labels = c("Short", "Long"))
# df_other_outcomes$good_title <- factor(df_other_outcomes$good_title,
#                         levels = c(0,1),
#                         labels = c("Bad","Good"))

bar_chart_other_outcomes <- function(df) {
  plt <- df %>% 
    pivot_longer(c(long_petition, good_title), names_to="attribute_name", values_to="attribute_value") %>% 
    pivot_longer(c(subject_matter_expert,author_committed, persuade_undecided,
                    motivate_reader)) %>% 
    mutate(value = factor(value, levels = c(disagree_vals, agree_vals), ordered=TRUE)) %>% 
    mutate(name_nice = case_when(name == 'subject_matter_expert' ~ 'Author is a subject matter expert...',
                                  name == 'author_committed' ~ 'Author is committed to the cause...',
                                  name == 'persuade_undecided' ~ 'Petition can persuade an undecided reader...',
                                  name == 'motivate_reader' ~ 'Petition can motivate a reader...')) %>%  
    group_by(attribute_name, attribute_value, name_nice, value) %>% 
    summarize(n = n()) %>% 
    group_by(name_nice, attribute_name, attribute_value) %>% 
    mutate(pct = 100*n/sum(n)) %>% 
    ungroup() %>% 
    mutate(attribute_name = if_else(attribute_name == 'good_title', 'Good title',
                                    'Long petition'),
           attribute_value = if_else(attribute_value == 1, 'Yes', 'No')) %>% 
    ggplot(aes(name_nice, pct, fill=value)) +
    geom_col(position="stack") +
    theme_minimal() +
    scale_fill_manual(values=cbPalette) +
    facet_grid(attribute_name ~ attribute_value,
               scales = "free_y", space = "free") +
    labs(x = "Outcome",
         y = "Percent",
         fill="")  +
    theme(axis.text.x = element_text(angle = -90, vjust = 0.5, hjust=1))
    print(plt)
  ggsave('other_outcomes.pdf', height=8, width=10)
}

bar_chart_other_outcomes(df_other_outcomes)
```

## Interaction with AI Priming

```{r}
mod_interaction <- glm(
    selected_petition ~ long_petition:AI_primed + good_title:AI_primed + long_petition + good_title, data = df,
    family = binomial(link = "logit")
  ) 

tidy(mod_interaction)

# formatting
stargazer(mod_interaction, title='Fully interacted model',
          dep.var.labels=c("Selected petition"),
          covariate.labels=c("Long",
                             "Good title",
                             "Long x AI primed",
                             "Good title x AI primed"),
          omit.stat=c("LL","ser","f"), ci=TRUE, ci.level=0.95, single.row=TRUE)
```

```{r}
mod_interaction_length <- glm(
    selected_petition ~ long_petition:AI_primed + long_petition + AI_primed, data = df,
    family = binomial(link = "logit")
  ) 

tidy(mod_interaction_length)

df_ai_primed_subg <- df %>% 
  group_by(long_petition, AI_primed) %>% 
  summarize(avg = mean(selected_petition, na.rm = TRUE)) %>% 
  pivot_wider(names_from = "AI_primed", values_from = "avg") %>% 
  mutate(diff = `1` - `0`)
df_ai_primed_subg

mms_mfx <- predictions(
  mod_interaction_length,
  newdata = datagrid(long_petition = unique, AI_primed = unique)
)

mms_mfx_diff <- predictions(
  mod_interaction_length,
  newdata = datagrid(long_petition = unique, AI_primed = unique),
  by=c("long_petition", "AI_primed"),
  hypothesis = difference ~ sequential
) %>% 
  as_tibble() %>% 
  filter(hypothesis %in% c("(0 1) - (0 0)", "(1 1) - (1 0)")) %>% 
  mutate(long_petition = if_else(hypothesis == '(0 1) - (0 0)', 'Short', 'Long'))

mms_mfx
```

```{r}
mms_plt <- mms_mfx %>% 
  mutate(estimate_nice = case_when(
    estimate != 0 ~ label_percent()(estimate),
    estimate == 0 ~ NA
  ),
  AI_primed = factor(AI_primed, levels=c(0,1), labels=c("Not AI primed", "AI primed")),
  long_petition = factor(long_petition, levels=c(0,1), labels=c("Short", "Long"))) %>% 
  ggplot(aes(x = estimate, y = long_petition, color=AI_primed)) +
  geom_vline(xintercept = 0.5) +
  geom_pointrange(aes(xmin = conf.low, xmax = conf.high)) +
  geom_label(
    aes(label = estimate_nice), 
    position = position_dodge(width = -1.2),
    size = 3.5, show.legend = FALSE
  ) +
  scale_x_continuous(labels = label_percent()) +
  scale_color_manual(values = cbPalette) +
  labs(
    x = "Marginal means",
    y = NULL,
    color = NULL,
    title = "Marginal means by AI priming"
  ) +
  facet_wrap(vars("long_petition")) +
  theme(
    legend.position = "bottom",
    legend.justification = "left",
    legend.margin = margin(l = -7, t = -5)
  ) +
  theme_minimal()
mms_plt
ggsave("marginal_means_AIprimed.pdf")
```

```{r}
mms_mfx_diff_plt <- mms_mfx_diff %>% 
  mutate(estimate_nice = label_amce(estimate)) %>% 
  ggplot(aes(x = estimate, y = long_petition)) +
  geom_vline(xintercept = 0) +
  geom_pointrange(aes(
    xmin = conf.low, xmax = conf.high, 
    color = "AI priming − No AI priming"
  )) +
  geom_label(
    aes(label = estimate_nice), size = 3.5,
    nudge_y = 0.3, color = cbPalette[1]
  ) +
  scale_x_continuous(labels = label_pp) +
  scale_color_manual(values = cbPalette) +
  labs(
    x = "Difference in marginal means",
    y = "",
    color = "",
    title = "Difference in marginal means by AI priming"
  ) +
  theme(
    legend.position = "bottom",
    legend.justification = "left",
    legend.margin = margin(l = -7, t = -5)
  ) +
  theme_minimal()

mms_mfx_diff_plt
ggsave("marginal_means_AIprimed.pdf")
```





